<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css2?family=Cookie&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap"
    rel="stylesheet">
<?php $js = $this->getJs(); ?>
<?php if (count($js) > 0): ?>
    <?php foreach ($js as $_js): ?>
        <script type="" src="<?php echo $_js; ?>"></script>
    <?php endforeach; ?>
<?php endif; ?>

<?php $css = $this->getCss(); ?>
<?php if (count($css) > 0): ?>
    <?php foreach ($css as $_css): ?>
        <link rel="stylesheet" href="<?php echo $_css ?>">
    <?php endforeach; ?>
<?php endif; ?>