<!-- Shop Section Begin -->
<?php
print_r($this->getCategores);
?>
<section class="shop spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="shop__sidebar">
                    <div class="sidebar__categories">
                        <div class="section-title">
                            <h4>Categories</h4>
                        </div>
                        <div class="categories__accordion">
                            <div class="accordion" id="accordionExample">
                                <?php
                                foreach ($this->getCategores() as $category) { ?>
                                    <div class="card">
                                        <div class="card-heading active">
                                            <a data-toggle="collapse" data-target="#collapseOne"
                                                href="<?php echo $this->getUrl('catalog/category/view') . "?id=" . $category->getCategoryId(); ?>">
                                                <?php echo $category->getCategoryName(); ?>
                                            </a>
                                        </div>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-9 col-md-9">
                <div class="row">
                    <?php
                    foreach ($this->getProducts() as $product) { ?>
                        <div class="col-lg-4 col-md-6">
                            <div class="product__item">
                                <div class="product__item__pic set-bg" data-setbg="">
                                    <img src="<?php echo $this->getMediaUrl('product/' . $product->getImageLink()) ?>">
                                    <div class="label new">New</div>
                                    <ul class="product__hover">
                                        <li><a
                                                href="<?php echo $this->getUrl('catalog/product/view') . "?id=" . $product->getProductId(); ?>"><span
                                                    class="fa fa-eye"></span></a></li>
                                        <li><a href="#"><span class="fa fa-heart"></span></a></li>
                                    </ul>
                                </div>
                                <div class="product__item__text">
                                    <h6><a href="#">
                                            <?php echo $product->getName() ?>
                                        </a></h6>
                                    <div class="rating">
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                        <i class="fa fa-star"></i>
                                    </div>
                                    <div class="product__price">
                                        <?php echo $product->getPrice() ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                    <?php } ?>
                    <div class="col-lg-12 text-center">
                        <div class="pagination__option">
                            <a href="#">1</a>
                            <a href="#">2</a>
                            <a href="#">3</a>
                            <a href="#"><i class="fa fa-angle-right"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>