<div class="slidebar">
    <div class="logo">
        <a href=""></a>
    </div>
    <ul>
        <li><a href="<?php echo $this->getUrl('admin/user/dashboard') ?>" id="targeted">dashboard</a></li>
        <li><a href="<?php echo $this->getUrl('admin/catalog_product/list') ?>">Products</a></li>
        <li><a href="<?php echo $this->getUrl('admin/catalog_category/list') ?>">Categorys</a></li>
        <li><a href="<?php echo $this->getUrl('admin/order/list') ?>">Orders</a></li>
        <li><a href="<?php echo $this->getUrl('admin/banner/list') ?>">Banners</a></li>
        <li><a href="#comments">comments</a></li>
        <li><a href="#widgets">widgets</a></li>
        <li><a href="#plugins">plugins</a></li>
        <li><a href="#users">users</a></li>
        <li><a href="#tools">tools</a></li>
        <li><a href="#settings">settings</a></li>
    </ul>
</div>