<div class="container">
    <div class="title">Sing Up</div>
    <div class="content">
        <form action=<?php echo $this->getUrl('customer/account/save') ?> method="post">
            <div class="user-details">
                <div class="input-box">
                    <span class="details">First Name</span>
                    <input type="text" placeholder="Enter your first name" name="customer_account[first_name]" required>
                </div>
                <div class="input-box">
                    <span class="details">Last Name</span>
                    <input type="text" placeholder="Enter your last name" name="customer_account[last_name]" required>
                </div>
                <div class="input-box">
                    <span class="details">Email</span>
                    <input type="text" placeholder="Enter your email" name="customer_account[customer_email]" required>
                </div>
                <div class="input-box">
                    <span class="details">Phone Number</span>
                    <input type="text" placeholder="Enter your number" name="customer_account[billing_phone]" required>
                </div>
                <div class="input-box">
                    <span class="details">Password</span>
                    <input type="password" placeholder="Enter your password" name="customer_account[password]" required>
                </div>
                <div class="input-box">
                    <span class="details">Confirm Password</span>
                    <input type="password" placeholder="Confirm your password" required>
                </div>
            </div>
            <div class="gender-details">
                <input type="radio" name="customer_account[gender]" id="dot-1">
                <input type="radio" name="customer_account[gender]" id="dot-2">
                <input type="radio" name="customer_account[gender]" id="dot-3">
                <span class="gender-title">Gender</span>
                <div class="category">
                    <label for="dot-1">
                        <span class="dot one"></span>
                        <span class="gender">Male</span>
                    </label>
                    <label for="dot-2">
                        <span class="dot two"></span>
                        <span class="gender">Female</span>
                    </label>
                    <label for="dot-3">
                        <span class="dot three"></span>
                        <span class="gender">other</span>
                    </label>
                </div>
            </div>
            <div class="box-terms">
                <input type="checkbox" name="Terms" name="customer_account[category_name]" required> &nbsp; I accept the
                terms
                and conditions
            </div>
            <div class="button">
                <input type="submit" value="Register">
            </div>
        </form>
        <div>
            <a class="signup__link" href="<?php echo $this->getUrl('customer/account/login') ?>">I am already a member
                ?</a>
        </div>
    </div>