<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <?php echo $this->getChildHtml('head'); ?>
</head>

<body>
    <div class="sidebar">
        <?php echo $this->getChildHtml('sidebar'); ?>
    </div>
    <div class="content">
        <?php echo $this->getChildHtml('content'); ?>
    </div>
</body>

</html>