<?php

?>
<div class="box">
    <div class="container">
        <div class="title_details">
            <div class="title">Product Information</div>
        </div>
        <div class="content">
            <table>
                <tr>
                    <th>Product Id</th>
                    <th>Product Name</th>
                    <th>Product SKU</th>
                    <th>Category</th>
                    <th>Edit</th>
                    <th>delete</th>
                </tr>
                <tr>
                    <td class='column'></td>
                    <td class='column'></td>
                    <td class='column'></td>
                    <td class='column'></td>
                    <td class='btn'></a></td>
                    <td class='btn'></td>

                </tr>
            </table>
        </div>
    </div>
</div>