<?php
$category = $this->getCategory();
?>
<div class="quick-press">
    <h4>Category Form</h4>
    <form action="" method="post">
        <input type="hidden" id="category_id" name="catalog_category[category_id]"
            value="<?php echo $category->getCategoryId() ?>">

        <input type="text" name="catalog_category[category_name]" value="<?php echo $category->getCategoryName() ?>"
            placeholder="Category Name" />
        <select class="dropdown" id=" status" name="catalog_category[status]" ?>

            <?php
            $status = [1 => "Enabled", 0 => "Disabled"];
            foreach ($status as $key => $item) {
                echo '<option value="' . $key . '" ' . (($category->getStatus() == $item) ? 'selected' : '') . '>' . $item . '</option>';
            }
            ?>
        </select>
        <button type="submit" class="submit" name="submit">Save</button>
    </form>
</div>