<?php
$categoryCollection = Mage::getModel('catalog/category')->getCollection();
echo get_class($this);
// $categoryModel = Mage::getModel('catalog/category');
// print_r($categoryCollection->getData());
// $categoryCollection->addFieldToFilter('name', 'category1');
// $categoryCollection->addFieldToFilter('category_id', ['in' => [1, 2, 3]]);
// $categoryCollection->addFieldToFilter('sku', ['like' => '%a']);
?>
<div class="box">
    <div class="container">
        <div class="sub_container">
            <div class="title_details">
                <div class="title">Category Information</div>
            </div>
            <div class="insert_button">
                <a href="form">
                    <button class="button-insert" role="button">Insert</button>
                </a>
            </div>
        </div>
        <div class="container">
            <ul class="responsive-table">
                <li class="table-header">
                    <div class="col col-1">Category Id</div>
                    <div class="col col-2">Category Name</div>
                    <div class="col col-3">Status</div>
                    <div class="col col-5">Edit</div>
                    <div class="col col-6">Delete</div>
                </li>
                <?php
                foreach ($categoryCollection->getData() as $category) {

                    ?>

                    <li class="table-row">
                        <div class="col col-1" data-label="Category Id">
                            <?php $id = $category->getCategoryId();
                            echo $id;
                            ?>
                        </div>
                        <div class="col col-2" data-label="Category Name">
                            <?php echo $category->getCategoryName(); ?>
                        </div>
                        <div class="col col-3" data-label="Status">
                            <?php echo $category->getStatus();
                            ?>
                        </div>
                        <div class="col col-5" data-label="Edit"><a
                                href="form?id=<?php echo $category->getCategoryId(); ?>">
                                <button class="button-edit" role="button">Edit</button></a></div>
                        <div class="col col-6" data-label="Delete"><a
                                href="delete?id=<?php echo $category->getCategoryId(); ?>">
                                <button class="button-delete" role="button">Detele</button></a></div>
                    </li>
                    <?php
                }
                ?>
            </ul>
        </div>
    </div>
</div>