<div>
    <?php
    foreach ($this->getItems() as $_items) {
        if ($_items) {
            foreach ($_items as $_item) {
                ?>

                <div data-id="mo-card" class="_3FkKcv">
                    <div class="_2GRc4O">
                        <div class="_11eueq">
                            <img class="bzr_ez _3hlRdh oYjghn"
                                src="<?php echo $this->getMediaUrl('product/' . $_item->getProduct()->getImageLink()) ?>">
                        </div>
                        <div class="_1wkQnM">
                            <span class="yxF9fy" style="color: rgb(255, 159, 0);">Delivered</span>
                            <span class="_2NmcYX">
                                <span class="_17gZxC">
                                    <?php echo $_item->getProduct()->getName() ?>
                                </span>
                            </span>
                        </div>
                        <a href="<?php echo $this->getUrl('customer/order/view') . "?id=" . $_item->getOrderId() ?>"><i
                                class="fa fa-arrow-right" aria-hidden="true"></i></a>
                    </div>
                </div>
                <?php
            }
        }
    }
    ?>
</div>