<div class="_1BQvsN">
    <div class="_3WsTgQ">
        <div class="_3E8aIl _2Pt11E">
            <div class="_2Hbwpg">
                <div class="_2K6hZO">
                    <div class="col-3-12 Oqho6V">
                        <div class="row" style="position: relative;">
                            <div class="col-4-12 _1mMlza">
                                <a href="/onego-business-compact-22-l-laptop-backpack/p/itmf97627629ef0a?pid=BKPG53CGFG2ANVUS&amp;lid=LSTBKPG53CGFG2ANVUSOVHE99"
                                    target="_blank" rel="noopener noreferrer" previewlistener="true">
                                    <div class="CXW8mj" style="height: 75px; width: 75px;">
                                        <img loading="lazy" class="_396cs4" alt=""
                                            src="<?php echo $this->getMediaUrl('product/' . $this->getItem()->getProduct()->getImageLink()) ?>">
                                    </div>
                                </a>
                            </div>
                            <div class="col-8-12">
                                <a class="_2KpZ6l row _3hTjfv"
                                    href="/onego-business-compact-22-l-laptop-backpack/p/itmf97627629ef0a?pid=BKPG53CGFG2ANVUS&amp;lid=LSTBKPG53CGFG2ANVUSOVHE99"
                                    target="_blank" previewlistener="true">
                                    <?php echo $this->getItem()->getProduct()->getName() ?>

                                </a>
                                <div class="row _1k5oiV">
                                    <span class="_3kfmpa">
                                        <span class="_1k5oiV">Quantity: </span>
                                        <span class="_5CyX2n">
                                            <?php echo $this->getItem()->getQty() ?>
                                        </span>
                                    </span>
                                    <span class="_3kfmpa"></span>
                                </div>
                                <div class="row _1k5oiV">
                                    <span class="_1k5oiV _3NgwL_">Price: </span>
                                    <span class="_5CyX2n">
                                        <?php echo $this->getItem()->getPrice() ?>
                                    </span>
                                </div>
                                <div class="_22HsHK">
                                    <div class="_1zIybI">
                                        <div class="gAEbPh">
                                            <?php echo $this->getItem()->getRowTotal() ?>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr />
                    <div class="col-6-12 _3dL9lb">
                        <div class="kKX2Ow">
                            <div class="_1ZJv_G"><span class="_3jRtMt">Shipping Address</span></div>
                            <div class="ltnpAV">
                                <div class="_23g6G-">
                                    <div class="HfawVC">
                                        <?php echo $this->getCustomer()->getCustomerEmail() ?>
                                    </div>
                                </div>
                                <div>
                                    <?php echo $this->getCustomer()->getFirstName();
                                    echo ' ';
                                    echo $this->getCustomer()->getLastName(); ?>
                                </div>
                                <div class="_10YZ6u">
                                    <?php echo $this->getAddress()->getShippingAddress() . ',' . $this->getAddress()->getShippingCity() . '-' . $this->getAddress()->getShippingPincode() ?>
                                </div>
                                <div class="_23g6G- _2rcD-x">
                                    <div><span class="HfawVC">Phone number</span>
                                        <div class="_Fqqjs">
                                            <?php echo $this->getCustomer()->getShippingPhone() ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="kKX2Ow">
                            <div class="_1ZJv_G"><span class="_3jRtMt">Billing Address</span></div>
                            <div class="ltnpAV">
                                <div class="_23g6G-">
                                    <div class="HfawVC">
                                        <?php echo $this->getCustomer()->getCustomerEmail() ?>
                                    </div>
                                </div>
                                <div>
                                    <?php echo $this->getCustomer()->getFirstName();
                                    echo ' ';
                                    echo $this->getCustomer()->getLastName(); ?>
                                </div>
                                <div class="_10YZ6u">
                                    <?php echo $this->getAddress()->getBillingAddress() . ',' . $this->getAddress()->getBillingCity() . '-' . $this->getAddress()->getBillingPincode() ?>
                                </div>
                                <div class="_23g6G- _2rcD-x">
                                    <div><span class="HfawVC">Phone number</span>
                                        <div class="_Fqqjs">
                                            <?php echo $this->getCustomer()->getBillingPhone() ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>