<?php
$bannerCollection = Mage::getModel('banner/banner')->getCollection();
foreach ($bannerCollection->getData() as $data) {
    $title = $data->getBannerTitle();
    $image = $data->getBannerImage();
}
?>
<section id="home">
    <div class="home_page ">
        <div class="home_img ">
            <img src="<?php echo Mage::getMediaUrl('banner/' . $image); ?>" alt="Banner">
        </div>
    </div>
</section>