<?php
$product = $this->getProduct();
$categoryModel = Mage::getModel('catalog/category');
$categorys = $categoryModel->getCategoryIdName();
$selectedCategory = $categoryModel->getCategoryNameById($categorys, $product);
?>

<div class="quick-press">
    <h4>Product Information</h4>
    <form action="<?php echo $this->getUrl('admin/catalog_product/save') ?>" method="post">
        <input type="hidden" id="product_id" name="catalog_category[product_id]"
            value="<?php echo $product->getProductId() ?>">
        <input type="text" name="catalog_product[sku]" value="<?php echo $product->getSku() ?>" placeholder="Sku">
        <input type="text" name="catalog_product[name]" value="<?php echo $product->getName() ?>" placeholder="name">
        <input type="text" name="catalog_product[color]" value="<?php echo $product->getColor() ?>" placeholder="color">
        <input type="text" name="catalog_product[size]" value="<?php echo $product->getSize() ?>" placeholder="size">
        <textarea name="catalog_product[description]" placeholder="description" cols="30"
            rows="5"><?php echo $product->getDescription() ?></textarea>
        <input type="file" name="catalog_product[image_link]" value="<?php echo $product->getImageLink() ?>"
            placeholder="image link">
        <input type="file" name="catalog_product[link]" value="<?php echo $product->getLink() ?>" placeholder="link">
        <input type="number" name="catalog_product[price]" value="<?php echo $product->getPrice() ?>" min=1
            placeholder="Price">
        <input type="number" name="catalog_product[mfr_cost]" value="<?php echo $product->getMfrCost() ?>" min=1
            placeholder="mfr cost">
        <input type="number" name="catalog_product[shipping_cost]" min=1
            value="<?php echo $product->getShippingCost() ?>" placeholder="shipping cost">
        <input type="number" min=1 name="catalog_product[total_cost]" value="<?php echo $product->getTotalCost() ?>"
            placeholder="total cost">
        <input type="number" min=1 name="catalog_product[margin_percentage]"
            value="<?php echo $product->getMarginPercentage() ?>" placeholder="Margin Percentage">
        <input type="number" min=1 name="catalog_product[min_price]" value="<?php echo $product->getMinPrice() ?>"
            placeholder="min price">
        <select name="catalog_product[status]">
            <?php
            $status = [1 => "Enabled", 0 => "Disabled"];
            foreach ($status as $key => $item) {
                echo '<option value="' . $key . '" ' . (($product->getStatus() == $item) ? 'selected' : '') . '>' . $item . '</option>';
            }
            ?>
        </select>
        <select name=" catalog_product[category_id]">
            <?php
            foreach ($categorys as $key => $value) {
                echo '<option value="' . $key . '" ' . ($selectedCategory == $value ? ' selected' : '') . '>' . $value
                    . '</option>';
            } ?>
        </select>
        <button type="submit" class="submit" name="submit">Save</button>
    </form>
</div>