<?php
$productCollection = Mage::getModel('catalog/product')->getCollection();
$categoryModel = Mage::getModel('catalog/category');
$categoryNames = $categoryModel->getCategoryIdName();
// $categoryCollection = Mage::getModel('catalog/category')->getCollection();
$productCollection->addFieldToFilter('name', 'product 5');
// $productCollection->addFieldToFilter('product_id', ['in' => [1, 2, 3]]);
// $productCollection->addFieldToFilter('sku', ['like' => '%a']);
?>
<div class="box">
    <div class="container">
        <div class="sub_container">
            <div class="title_details">
                <div class="title">Product Information</div>
            </div>
            <div class="insert_button">
                <a href="form">
                    <button class="button-insert" role="button">Insert</button>
                </a>
            </div>
        </div>
        <div class="container">
            <ul class="responsive-table">
                <li class="table-header">
                    <div class="col col-1">Product Name</div>
                    <div class="col col-1">Product SKU</div>
                    <div class="col col-1">Color</div>
                    <div class="col col-1">Status</div>
                    <div class="col col-1">Category</div>
                    <div class="col col-1">Edit</div>
                    <div class="col col-1">Delete</div>
                </li>
                <?php
                foreach ($productCollection->getData() as $product) {
                    ?>
                    <li class="table-row">

                        <div class="col col-1" data-label="Product Name">
                            <?php echo $product->getName(); ?>
                        </div>
                        <div class="col col-1" data-label="Product SKU">
                            <?php echo $product->getSku(); ?>
                        </div>
                        <div class="col col-1" data-label="Category">
                            <?php echo $product->getColor(); ?>
                        </div>
                        <div class="col col-1" data-label="Status">
                            <?php echo $product->getStatus(); ?>
                        </div>
                        <div class="col col-1" data-label="category">
                            <?php
                            $selectedCategory = $categoryModel->getCategoryNameById($categoryNames, $product);
                            echo $selectedCategory;
                            ?>
                        </div>
                        <div class="col col-1" data-label="Edit"><a href="form?id=<?php echo $product->getProductId(); ?>">
                                <button class="button-edit" role="button">Edit</button></a></div>
                        <div class="col col-1" data-label="Delete"><a
                                href="delete?id=<?php echo $product->getProductId(); ?>">
                                <button class="button-delete" role="button">Detele</button></a></div>
                    </li>
                    <?php
                }
                ?>
            </ul>
        </div>
    </div>
</div>