<?php
$productCollection = Mage::getModel('catalog/product')->getCollection();
// $productCollection->addFieldToFilter('name', 'abc');
// $productCollection->addFieldToFilter('product_id', ['in' => [1, 2, 3]]);
// $productCollection->addFieldToFilter('sku', ['like' => '%a']);
?>
<div class="box">
    <div class="container">
        <div class="title_details">
            <div class="title">Product Information</div>
        </div>
        <div class="content">
            <table>
                <tr>
                    <th>Product Id</th>
                    <th>Product Name</th>
                    <th>Product SKU</th>
                    <th>Category</th>
                    <th>Edit</th>
                    <th>delete</th>
                </tr>
                <?php
                foreach ($productCollection->getData() as $product) {
                    ?>

                    <tr>
                        <td class='column'>
                            <?php echo $product->getProductId(); ?>
                        </td>
                        <td class='column'>
                            <?php echo $product->getName(); ?>
                        </td>
                        <td class='column'>
                            <?php echo $product->getSku(); ?>
                        </td>
                        <td class='column'>
                            <?php echo $product->getCategoryId(); ?>
                        </td>
                        <td class='btn'></a></td>
                        <td class='btn'></td>

                    </tr>
                    <?php
                }
                ?>
            </table>
        </div>
    </div>
</div>